# Generated by Django — WO-032 rename Python field; DB column Asessment unchanged.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claim", "0037_claimjob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="asessment",
            new_name="assessment",
        ),
    ]
