"""Claim create/update persistence and input validation."""

import importlib
import logging
from typing import Callable, Dict

from django.core.exceptions import ValidationError
from django.db.models import F, FloatField, OuterRef, Subquery, Sum
from django.db.models.functions import Coalesce
from django.utils.translation import gettext as _

from claim.apps import ClaimConfig
from claim.models import Claim, ClaimItem, ClaimService
from claim.utils import process_items_relations, process_services_relations

logger = logging.getLogger(__name__)


def update_sum_claims(claim):
    service_asked = Subquery(
        ClaimItem.objects.filter(claim=OuterRef("pk"))
        .filter(legacy_id__isnull=True)
        .values("claim_id")
        .annotate(item_sum=Sum(F("price_asked") * F("qty_provided")))
        .values("item_sum")
        .order_by()[:1],
        output_field=FloatField(),
    )
    item_asked = Subquery(
        ClaimService.objects.filter(claim=OuterRef("pk"))
        .filter(legacy_id__isnull=True)
        .values("claim_id")
        .annotate(service_sum=Sum(F("price_asked") * F("qty_provided")))
        .values("service_sum")
        .order_by()[:1],
        output_field=FloatField(),
    )
    Claim.objects.filter(id=claim.id).update(
        claimed=Coalesce(item_asked, 0) + Coalesce(service_asked, 0)
    )


def check_unique_claim_code(code):
    if Claim.objects.filter(code=code, validity_to__isnull=True).exists():
        return [{"message": "Claim code %s already exists" % code}]
    return []


def reset_claim_before_update(claim):
    claim.date_to = None
    claim.icd_1 = None
    claim.icd_2 = None
    claim.icd_3 = None
    claim.icd_4 = None
    claim.refer_from = None
    claim.refer_to = None
    claim.referral_code = None
    claim.guarantee_id = None
    claim.explanation = None
    claim.adjustment = None
    claim.json_ext = None


def _autogenerate_claim_code():
    module_name, function_name = "[undefined]", "[undefined]"
    try:
        claim_code_function = _get_autogenerating_func()
        return claim_code_function(ClaimConfig.autogenerated_claim_code_config)
    except ImportError as e:
        logger.error(
            f"Error: Could not import module '{module_name}' for claim code autogeneration"
        )
        raise e
    except AttributeError as e:
        logger.error(
            f"Error: Could not find function '{function_name}' in module '{module_name}' for claim code autogeneration"
        )
        raise e


def _get_autogenerating_func() -> Callable[[Dict], Callable]:
    module_name, function_name = ClaimConfig.autogenerate_func.rsplit(".", 1)
    module = importlib.import_module(module_name)
    return getattr(module, function_name)


def set_reduced_attr(obj, data, exclusions):
    for key in data:
        if key not in exclusions:
            setattr(obj, key, data[key])


def claim_create_items_and_services(claim, data, user):
    items = data.pop("items") if "items" in data else []
    services = data.pop("services") if "services" in data else []
    claimed = 0
    claimed += process_items_relations(user, claim, items)
    claimed += process_services_relations(user, claim, services)
    claim.claimed = claimed
    claim.save()


def claim_create(data, user, autogenerate_code=False):
    restore = data.pop("restore", None)
    autogenerate = data.pop("autogenerate", None)
    if autogenerate is None:
        autogenerate = autogenerate_code
    if restore:
        from claim.claim_restore import validate_restore_request

        data["restore"] = validate_restore_request(restore, user)

    if autogenerate:
        data["code"] = _autogenerate_claim_code()
    data["audit_user_id"] = user.id_for_audit
    claim = Claim()
    set_reduced_attr(claim, data, ["items", "services"])
    claim.save()
    claim_create_items_and_services(claim, data, user)
    return claim


def claim_update(claim, data, user):
    claim.save_history()
    reset_claim_before_update(claim)
    set_reduced_attr(claim, data, ["items", "services"])
    from core.utils import TimeUtils

    claim.items.update(validity_to=TimeUtils.now())
    claim.services.update(validity_to=TimeUtils.now())
    claim_create_items_and_services(claim, data, user)
    return claim


def validate_number_of_additional_diagnoses(incoming_data):
    from claim.referral_diagnosis import count_additional_diagnoses_in_data

    return (
        count_additional_diagnoses_in_data(incoming_data)
        <= ClaimConfig.additional_diagnosis_number_allowed
    )


def validate_claim_data(data, user):
    services = data.get("services") if "services" in data else []
    incoming_code = data.get("code")
    claim_uuid = data.get("uuid", None)
    restore = data.get("restore", None)
    current_claim = Claim.objects.filter(uuid=claim_uuid).first()
    current_code = current_claim.code if current_claim else None

    if restore:
        from claim.claim_restore import validate_restore_request

        validate_restore_request(restore, user)

    elif current_claim is not None and current_claim.status not in (
        Claim.STATUS_CHECKED,
        Claim.STATUS_ENTERED,
    ):
        raise ValidationError(_("mutation.claim_not_editable"))

    if not validate_number_of_additional_diagnoses(data):
        raise ValidationError(_("mutation.claim_too_many_additional_diagnoses"))

    if ClaimConfig.claim_validation_multiple_services_explanation_required:
        for service in services:
            if service["qty_provided"] > 1 and not service.get("explanation"):
                raise ValidationError(_("mutation.service_explanation_required"))

    if len(incoming_code) > ClaimConfig.max_claim_length:
        raise ValidationError(_("mutation.code_name_too_long"))

    if (
        not restore
        and current_code != incoming_code
        and check_unique_claim_code(incoming_code)
    ):
        raise ValidationError(_("mutation.code_name_duplicated"))


def update_or_create_claim(data, user):
    validate_claim_data(data, user)
    claim_uuid = data.pop("uuid", None)
    if claim_uuid:
        claim = Claim.objects.get(uuid=claim_uuid)
        claim = claim_update(claim, data, user)
    else:
        claim = claim_create(data, user)
    return claim
